Update brands.txt
chris-mosley/AmazonBrandFilterList pull request #55
Opened 2024-12-31 00:30 UTC by ForeverFloating

Adding brands that were listed in sidebar after searching for "battery organizer"

2024-12-31 06:43 UTC, chris-mosley commented
uxcell and KEEPOW both look kind sus to me.  are you sure about them?

2024-12-31 22:55 UTC, ForeverFloating commented
I did find websites for both the companies you listed, but no, I am not sure about their authenticity.

- KEEPOW: [https://mykeepow.com/](https://mykeepow.com/)
- uxcell: [https://www.uxcell.com/index.php](https://www.uxcell.com/index.php)

2025-01-01 02:18 UTC, chris-mosley requested changes
Yeah, checking them out they still look like slightly higher effort drop shippers to me.  please remove keepow and uxcell and we can get these merged.

Thanks!

2025-01-01 18:30 UTC, chris-mosley approved these changes

2025-01-01 18:30 UTC, merged

2025-01-01 18:31 UTC, chris-mosley commented
Merged.  Thanks!